FROM python:3.8-alpine
WORKDIR /api
COPY . .
RUN apk update
RUN 
ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future pip install --upgrade numpy
RUN gcc g++ subversion python3-dev
RUN pip install --no-cache-dir -r requirements_api.txt
EXPOSE 5000
ENTRYPOINT [ "uvicorn", "app:app", "--host", "0.0.0.0", "--reload" ]
